# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary

max_jobs: 1


# Adapt as necessary starting from here
# Based on https://github.com/tidyverse/dplyr/blob/f12d245403de13866db6c11b0fdb91b1c38f9b05/appveyor.yml

environment:
  global:
    WARNINGS_ARE_ERRORS: 1
    R_ARCH: x64
    USE_RTOOLS: true
    PKGTYPE: source

build_script:
  - nuget install secure-file -ExcludeVersion
  - secure-file\tools\secure-file -decrypt inst\extdata\sql.yamlwin.enc -secret %securepwd%
  - move inst\extdata\sql.yamlwin %USERPROFILE%\documents\sql.yaml
  - del inst\extdata\*.enc
  - travis-tool.sh install_github r-pkgs/remotes@9b38115c # https://github.com/tidyverse/dplyr/pull/2761
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

